{
 "title": "CloudOps API Monitoring Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CloudOps API Target Status",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(up{job=\"cloudops-api-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CloudOps API Available Replicas",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"cloudops\", deployment=\"cloudops-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CloudOps API Desired Replicas",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{namespace=\"cloudops\", deployment=\"cloudops-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Simulated Errors",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(cloudops_error_total)", "legendFormat": "Simulated errors" }
   ]
  },
  {
   "title": "CloudOps API Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(cloudops_request_total[1m]))",
     "legendFormat": "{{Request rate}}"
    }
   ]
  },
  {
   "title": "CloudOps API Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(cloudops_error_total[1m]))",
     "legendFormat": "{{Error rate}}"
    }
   ]
  },
  {
   "title": "CloudOps API CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  rate(\r\n    container_cpu_usage_seconds_total{\r\n      namespace=\"cloudops\",\r\n      container=\"cloudops-api\"\r\n    }[5m]\r\n  )\r\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CloudOps API Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  container_memory_working_set_bytes{\r\n    namespace=\"cloudops\",\r\n    container=\"cloudops-api\"\r\n  }\r\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "FastAPI Process Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (pod) (\r\n  process_resident_memory_bytes{\r\n    namespace=\"cloudops\",\r\n    job=\"cloudops-api-service\"\r\n  }\r\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}